// Generated by https://quicktype.io

import 'dart:convert';

import 'package:store_pro/product_store/model/product.dart';

IcecreamData icecreamDataFromJson(String str){
  final jsonData = json.decode(str);
  return IcecreamData.fromJson(jsonData);
}

String icecreamDataToJson(IcecreamData data){
  final dyn = data.toJson();
  return json.encode(dyn);
}

class IcecreamData {
  List<Icecream>? icecreams;

  IcecreamData({
    this.icecreams,
  });

  factory IcecreamData.fromJson(Map<String,dynamic> json) => IcecreamData(
    icecreams: List<Icecream>.from(json["icecreams"].map((x) => Icecream.fromJson(x))),
  );

  Map<String, dynamic> toJson() => {
    "icecreams": List<dynamic>.from(icecreams!.map((x) => x.toJson())),
  };

}

class Icecream extends Product {
  int id;
  String? category;
  String flavor;
  String? description;
  List<String>? toppings;
  num price;
  String? image;
  List<Ingredient> ingredients;

  Icecream({
    required this.id,
    this.category,
    required this.flavor,
    this.description,
    this.toppings,
    required this.price,
    this.image,
    required this.ingredients,
  });

  factory Icecream.fromJson(Map<String, dynamic> json) {
    return Icecream(
      id: json['id'],
      category: json['category'],
      flavor: json['flavor'],
      description: json['description'],
      toppings: json['toppings'] != null
        ? List<String>.from(json['toppings'])
        : null,
      price: json['price'] as num,
      image: json['image'],
      ingredients: json['ingredients'] = List<Ingredient>.from(json['ingredients'].map((x) => Ingredient.fromJson(x))),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'category': category,
      'flavor': flavor,
      'description': description,
      'toppings': toppings,
      'price': price,
      'image': image,
      'ingredients': List<dynamic>.from(ingredients.map((x) => x.toJson())),
    };
  }

  @override
  String toString() {
    return 'Name - $flavor, Price - $price';
  }

}

class Ingredient {
  String name;
  String quantity;

  Ingredient({
    required this.name,
    required this.quantity,
  });

  factory Ingredient.fromJson(Map<String, dynamic> json) {
    return Ingredient(
      name: json['name'],
      quantity: json['quantity'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'name': name,
      'quantity': quantity,
    };
  }

}
